In [ ]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [ ]:
dataset = pd.read_csv('rawdata.csv')

In [ ]:
dataset.head()

SAMPLE_ID  snp_0  snp_1  snp_2  ...  snp_9998  snp_9999  snp_10000  STATUS
0    HCB181      1      0      0  ...         2         1          2       1
1    HCB182      1      0      0  ...         2         2          2       2
2    HCB183      1      0      0  ...         2         1          2       2
3    HCB184      1      0      0  ...         2         1          2       2
4    HCB185      1      0      0  ...         2         2          2       1

[5 rows x 10003 columns]

In [ ]:
dataset.describe()

snp_0  snp_1  snp_2  snp_3  ...   snp_9998   snp_9999  snp_10000     STATUS
count   89.0   89.0   89.0   89.0  ...  89.000000  89.000000  89.000000  89.000000
mean     1.0    0.0    0.0    1.0  ...   1.898876   1.337079   1.853933   1.516854
std      0.0    0.0    0.0    0.0  ...   0.338612   0.475390   0.355175   0.502547
min      1.0    0.0    0.0    1.0  ...   0.000000   1.000000   1.000000   1.000000
25%      1.0    0.0    0.0    1.0  ...   2.000000   1.000000   2.000000   1.000000
50%      1.0    0.0    0.0    1.0  ...   2.000000   1.000000   2.000000   2.000000
75%      1.0    0.0    0.0    1.0  ...   2.000000   2.000000   2.000000   2.000000
max      1.0    0.0    0.0    1.0  ...   2.000000   2.000000   2.000000   2.000000

[8 rows x 10002 columns]

In [ ]:
y = np.asarray(dataset['STATUS'])
x = (dataset.drop('STATUS',1))
x = np.asarray(x.drop('SAMPLE_ID',1))

In [ ]:
for i in range(0,len(y)):
  y[i] = y[i]-1 
y

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)
x_test, x_validation, y_test, y_validation = train_test_split(x_test, y_test, test_size=0.33, random_state=0)

In [ ]:
x_test.shape

(12, 10001)

In [ ]:
x_train = x_train.reshape(71,10001,1)
x_test = x_test.reshape(-1,10001,1)
x_validation = x_validation.reshape(-1,10001,1)

In [ ]:
#check shape
x_train.shape

(71, 10001, 1)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Flatten
#create model
model = Sequential()
#add model layers
model.add(Conv1D(64, kernel_size=3, activation='relu',input_shape=(10001,1)))
model.add(Conv1D(32, kernel_size=3, activation='relu'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [ ]:
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, validation_data=(x_validation, y_validation), epochs=15)

Epoch 1/15
3/3 [==============================] - 14s 288ms/step - loss: 3.8027 - accuracy: 0.5262 - val_loss: 0.7843 - val_accuracy: 0.8333
Epoch 2/15
3/3 [==============================] - 0s 25ms/step - loss: 2.6326 - accuracy: 0.4941 - val_loss: 0.4545 - val_accuracy: 0.8333
Epoch 3/15
3/3 [==============================] - 0s 24ms/step - loss: 0.7666 - accuracy: 0.5364 - val_loss: 1.5264 - val_accuracy: 0.1667
Epoch 4/15
3/3 [==============================] - 0s 24ms/step - loss: 0.8325 - accuracy: 0.5598 - val_loss: 0.9995 - val_accuracy: 0.1667
Epoch 5/15
3/3 [==============================] - 0s 25ms/step - loss: 0.6917 - accuracy: 0.5465 - val_loss: 0.6750 - val_accuracy: 0.6667
Epoch 6/15
3/3 [==============================] - 0s 21ms/step - loss: 0.6445 - accuracy: 0.7561 - val_loss: 0.7093 - val_accuracy: 0.3333
Epoch 7/15
3/3 [==============================] - 0s 23ms/step - loss: 0.6103 - accuracy: 0.8616 - val_loss: 0.8013 - val_accuracy: 0.1667
Epoch 8/15
3/3 [=========

In [ ]:
#predict images in the test set
model = model.predict(x_test)

In [ ]:
#if the predicted model has a value greater than 0.5, then it will be converted to int 1 or so if it's lesser it will become 0
prediction = (model > 0.5).astype(int)
prediction

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [ ]:
#actual results for the images in test set
y_test

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, prediction)

0.4166666666666667