In [ ]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [ ]:
dataset = pd.read_csv('rawdata.csv')

In [ ]:
y = np.asarray(dataset['STATUS'])
x = (dataset.drop('STATUS',1))
x = np.asarray(x.drop('SAMPLE_ID',1))

In [ ]:
for i in range(0,len(y)):
  y[i] = y[i]-1 
y

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)
x_test, x_validation, y_test, y_validation = train_test_split(x_test, y_test, test_size=0.33, random_state=0)

In [ ]:
x_train.shape

(71, 10001)

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=64)
pca = pca.fit(x_train)
x_train = pca.transform(x_train)
x_test = pca.transform(x_test)
x_validation = pca.transform(x_validation)

In [ ]:
x_train = x_train.reshape(-1,64,1)
x_test = x_test.reshape(-1,64,1)
x_validation = x_validation.reshape(-1,64,1)

In [ ]:
#check shape
x_test.shape

(12, 64, 1)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Flatten
#create model
model = Sequential()
#add model layers
model.add(Conv1D(64, kernel_size=3, activation='relu',input_shape=(64,1)))
model.add(Conv1D(32, kernel_size=3, activation='relu'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [ ]:
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
#train the model
model.fit(x_train, y_train, validation_data=(x_validation, y_validation), epochs=15)

Epoch 1/15
3/3 [==============================] - 15s 279ms/step - loss: 0.7304 - accuracy: 0.5121 - val_loss: 0.7168 - val_accuracy: 0.3333
Epoch 2/15
3/3 [==============================] - 0s 15ms/step - loss: 0.6354 - accuracy: 0.7115 - val_loss: 0.7221 - val_accuracy: 0.3333
Epoch 3/15
3/3 [==============================] - 0s 16ms/step - loss: 0.5618 - accuracy: 0.8194 - val_loss: 0.7278 - val_accuracy: 0.3333
Epoch 4/15
3/3 [==============================] - 0s 16ms/step - loss: 0.5185 - accuracy: 0.8780 - val_loss: 0.7321 - val_accuracy: 0.0000e+00
Epoch 5/15
3/3 [==============================] - 0s 15ms/step - loss: 0.4689 - accuracy: 0.9109 - val_loss: 0.7345 - val_accuracy: 0.0000e+00
Epoch 6/15
3/3 [==============================] - 0s 16ms/step - loss: 0.4295 - accuracy: 0.9515 - val_loss: 0.7353 - val_accuracy: 0.3333
Epoch 7/15
3/3 [==============================] - 0s 16ms/step - loss: 0.3895 - accuracy: 0.9672 - val_loss: 0.7368 - val_accuracy: 0.3333
Epoch 8/15
3/3 [=

In [ ]:
#predict images in the test set
model = model.predict(x_test)

In [ ]:
model

array([[0.5319562 ],
       [0.35720566],
       [0.43457156],
       [0.6789144 ],
       [0.550798  ],
       [0.5782026 ],
       [0.45448235],
       [0.4109679 ],
       [0.5134526 ],
       [0.47348046],
       [0.44846782],
       [0.6090087 ]], dtype=float32)

In [ ]:
#if the predicted model has a value greater than 0.5, then it will be converted to int 1 or so if it's lesser it will become 0
prediction = (model > 0.5).astype(int)
prediction

array([[1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1]])

In [ ]:
#actual results for the images in test set
y_test

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, prediction)

0.5833333333333334